name = "manufacturing-erp-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "manufacturing-erp-db"
database_id = "30db7da4-c31f-43d8-9a5e-81eedbe93914"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGIN = "https://562dce40.manufacturing-erp-web.pages.dev"
